"""Local-first indexing pipeline for persisted document chunks."""

import re
from pathlib import Path

from app.core.config import Settings, get_settings
from app.indexing.backends import VectorIndexBackend
from app.indexing.models import IndexPreparationResult, LexicalIndexInput, VectorIndexInput
from app.models.schemas import DocumentChunk
from app.storage.service import LocalFileStorageService


class LocalManifestVectorBackend:
    """Default local vector backend that prepares serializable manifest records."""

    def prepare(self, inputs: list[VectorIndexInput]) -> list[dict[str, object]]:
        """Convert vector inputs into a backend-neutral manifest format.

        Why this function exists:
            The project needs a local-first vector preparation step now, but it
            should not hardcode one future embedding database. This backend
            simply serializes the embedding workload so another backend can be
            swapped in later.

        Parameters:
            inputs: Vector-ready chunk records generated by the indexing
                service.

        Returns:
            A list of serializable dictionaries containing the fields future
            vector backends typically need.

        Edge cases handled:
            Empty input returns an empty list, which keeps manifest writes
            deterministic for no-op indexing runs.
        """
        return [
            {
                "chunk_id": item.chunk_id,
                "document_id": item.document_id,
                "text": item.text,
                "metadata": item.metadata,
            }
            for item in inputs
        ]


class IndexingService:
    """Service for persisting chunks and preparing local index input manifests."""

    def __init__(
        self,
        *,
        storage: LocalFileStorageService | None = None,
        vector_backend: VectorIndexBackend | None = None,
        settings: Settings | None = None,
    ) -> None:
        """Initialize the indexing service with swappable storage and vector backends.

        Why this function exists:
            Index preparation needs two replaceable concerns: where local state
            is stored and how vector backends consume prepared inputs. The
            constructor makes both dependencies explicit instead of burying them
            in module globals.

        Parameters:
            storage: Optional storage backend used for local persistence.
            vector_backend: Optional vector backend used to shape vector inputs.
            settings: Optional validated application settings object.

        Returns:
            This initializer does not return a value; it stores the shared
            dependencies on the service instance.

        Edge cases handled:
            Default local implementations are supplied when dependencies are not
            passed, which keeps the local-first workflow simple.
        """
        self._settings = settings or get_settings()
        self._storage = storage or LocalFileStorageService(self._settings)
        self._vector_backend = vector_backend or LocalManifestVectorBackend()

    def _build_retrieval_metadata(self, chunk: DocumentChunk) -> dict[str, object]:
        """Assemble the metadata fields retrieval needs from one chunk.

        Why this function exists:
            The indexing stage is the last point where the code still has the
            fully typed ``DocumentChunk`` object. Capturing the chunk's
            retrieval-relevant provenance here keeps later retrieval code
            simple because it can load a single manifest record instead of
            reverse-engineering missing fields from multiple sources.

        Parameters:
            chunk: Concrete chunk record whose retrieval metadata should be
                copied into vector and lexical manifests.

        Returns:
            A new metadata dictionary containing both the original chunk
            metadata and the structured fields retrieval needs for result
            rendering, scoring filters, and provenance reporting.

        Edge cases handled:
            Existing chunk metadata is copied before enrichment so this helper
            never mutates caller-owned chunk objects; optional fields such as
            ``section_heading`` are stored even when ``None`` so downstream code
            can distinguish "missing" from "not provided".
        """
        # Start from a shallow copy so the indexing pipeline preserves caller
        # metadata while remaining free to add retrieval-specific fields.
        retrieval_metadata: dict[str, object] = dict(chunk.metadata)

        # Persist the chunk fields retrieval needs for filters, citations, and
        # debugging regardless of whether the upstream metadata included them.
        retrieval_metadata.update(
            {
                "source_type": chunk.source_type,
                "chunk_index": chunk.chunk_index,
                "char_start": chunk.char_start,
                "char_end": chunk.char_end,
                "section_heading": chunk.section_heading,
            }
        )

        # Return the enriched metadata so vector and lexical manifests stay in
        # sync for later hybrid retrieval.
        return retrieval_metadata

    def persist_chunks(self, document_id: str, chunks: list[DocumentChunk]) -> Path:
        """Persist chunk records before index preparation.

        Why this function exists:
            Persisting chunks separately from index preparation makes the
            indexing pipeline resumable and inspectable. It also keeps storage
            concerns separate from vector and lexical preparation.

        Parameters:
            document_id: Parent document identifier for the chunk batch.
            chunks: Chunk records to persist locally.

        Returns:
            The filesystem path of the written chunk file.

        Edge cases handled:
            Empty chunk lists still produce an explicit persisted file, which is
            useful when a document intentionally yields no indexable chunks.
        """
        result = self._storage.save_chunks(document_id, chunks)
        return result.path

    def build_vector_inputs(self, chunks: list[DocumentChunk]) -> list[VectorIndexInput]:
        """Prepare chunk records for a future vector index backend.

        Why this function exists:
            Vector backends typically need text, IDs, and metadata in a backend-
            specific shape. This method creates a backend-neutral input contract
            first so the actual vector store can be swapped later.

        Parameters:
            chunks: Chunk records that should be embedded and inserted into a
                vector backend.

        Returns:
            A list of ``VectorIndexInput`` records preserving chunk provenance.

        Edge cases handled:
            Empty input returns an empty list; metadata is copied rather than
            mutated so chunk objects remain stable for other callers.
        """
        return [
            VectorIndexInput(
                chunk_id=chunk.chunk_id,
                document_id=chunk.document_id,
                text=chunk.text,
                metadata=self._build_retrieval_metadata(chunk),
            )
            for chunk in chunks
        ]

    def build_lexical_inputs(self, chunks: list[DocumentChunk]) -> list[LexicalIndexInput]:
        """Prepare chunk records for lexical search indexing.

        Why this function exists:
            Hybrid retrieval often combines vector and lexical search. This
            method creates a simple lexical input shape now without forcing the
            codebase to commit to one lexical backend implementation.

        Parameters:
            chunks: Chunk records that should contribute to lexical search.

        Returns:
            A list of ``LexicalIndexInput`` records containing normalized text
            and simple term tokenization.

        Edge cases handled:
            Empty text yields an empty term list rather than raising, which keeps
            lexical preparation deterministic even for edge-case chunks.
        """
        lexical_inputs: list[LexicalIndexInput] = []
        for chunk in chunks:
            terms = re.findall(r"\b\w+\b", chunk.text.lower())
            lexical_inputs.append(
                LexicalIndexInput(
                    chunk_id=chunk.chunk_id,
                    document_id=chunk.document_id,
                    text=chunk.text,
                    terms=terms,
                    metadata=self._build_retrieval_metadata(chunk),
                )
            )
        return lexical_inputs

    def prepare_indexes(
        self,
        chunks: list[DocumentChunk],
        *,
        collection_name: str = "default",
        include_lexical: bool = True,
    ) -> IndexPreparationResult:
        """Prepare local vector and optional lexical index manifests from chunks.

        Why this function exists:
            The indexing stage needs to transform chunk records into the shapes
            future retrieval backends expect while keeping the implementation
            local-first today. This method writes the prepared manifests and a
            metadata summary so the run can be inspected or replayed.

        Parameters:
            chunks: Chunk records to include in the indexing batch.
            collection_name: Logical name for the prepared index collection.
            include_lexical: Whether lexical index preparation should also be
                performed alongside vector preparation.

        Returns:
            An ``IndexPreparationResult`` pointing to the persisted manifests.

        Edge cases handled:
            Empty chunk sets still produce explicit manifests; lexical
            preparation can be disabled cleanly without affecting vector
            preparation.
        """
        vector_inputs = self.build_vector_inputs(chunks)
        vector_records = self._vector_backend.prepare(vector_inputs)
        vector_result = self._storage.save_metadata(
            f"{collection_name}/vector_inputs.json",
            {"records": vector_records},
        )

        lexical_manifest_path: Path | None = None
        if include_lexical:
            lexical_inputs = self.build_lexical_inputs(chunks)
            lexical_result = self._storage.save_metadata(
                f"{collection_name}/lexical_inputs.json",
                {"records": [item.model_dump(mode="json") for item in lexical_inputs]},
            )
            lexical_manifest_path = lexical_result.path

        metadata_result = self._storage.save_metadata(
            f"{collection_name}/manifest.json",
            {
                "collection_name": collection_name,
                "chunk_count": len(chunks),
                "include_lexical": include_lexical,
                "vector_backend": self._vector_backend.__class__.__name__,
                "source_documents": sorted({chunk.document_id for chunk in chunks}),
            },
        )

        return IndexPreparationResult(
            chunk_count=len(chunks),
            vector_manifest_path=vector_result.path,
            lexical_manifest_path=lexical_manifest_path,
            metadata_manifest_path=metadata_result.path,
        )

    def index(
        self,
        document_id: str,
        chunks: list[DocumentChunk],
        *,
        collection_name: str = "default",
        include_lexical: bool = True,
    ) -> IndexPreparationResult:
        """Persist chunk records and prepare index manifests in one call.

        Why this function exists:
            Many callers want a single orchestration method that both writes
            chunk records and prepares local index inputs. This method provides
            that higher-level workflow while still using the separate helpers
            internally.

        Parameters:
            document_id: Parent document identifier for the chunk batch.
            chunks: Chunk records ready for persistence and index preparation.
            collection_name: Logical name used for manifest file organization.
            include_lexical: Whether lexical inputs should also be prepared.

        Returns:
            An ``IndexPreparationResult`` describing the generated manifests.

        Edge cases handled:
            Persistence happens before manifest preparation, which reduces the
            chance of ending up with index manifests that reference unpersisted
            chunks after a partial failure.
        """
        self.persist_chunks(document_id, chunks)
        return self.prepare_indexes(
            chunks,
            collection_name=collection_name,
            include_lexical=include_lexical,
        )
